# Python cimg 2.0 configuration file
#
# Check https://cimg.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  create_venv:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
          - v0-dependencies-{{ checksum "pyproject.toml" }}
          # don't fallback to using the latest cache if no exact match is found (restart from scratch
      - run: make venv
      # Save venv for later runs
      - save_cache:
          paths:
            - venv
          key: v0-dependencies-{{ checksum "pyproject.toml" }}
      # Save venv for other jobs
      - persist_to_workspace:
          root: venv
          paths:
            - '*'

  check_format:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: venv
      - run: make check_format

  lint:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: venv
      - run: make lint
      - store_test_results:
            path: test_results

  installable:
      docker:
        - image: cimg/python:3.6
      steps:
        - checkout
        - attach_workspace:
            at: venv
        - run: make installable

  test_coverage:
      docker:
        # circleci are deprecated according to https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034/32
        # but rsync fails to install on the new cimg.
        - image: cimg/python:3.6
      steps:
        - checkout
        - attach_workspace:
            at: venv
        - run: sudo apt-get update && sudo apt-get install --yes --no-install-recommends rsync
        - run: make test_coverage
        - store_test_results:
            path: test_results
        - store_artifacts:
            path: test_results/coverage_html

workflows:
  version: 2
  all_ci:
    jobs:
      - create_venv
      - check_format:
          requires:
            - create_venv
      - lint:
          requires:
            - create_venv
      - installable:
          requires:
            - create_venv
      - test_coverage:
          requires:
            - create_venv
